return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "helix",
    spec = {
      {
        mode = { "n", "x" },
        { "<leader>b", group = "Buffers", icon = "" },
        { "<leader>c", group = "Code", icon = "" },
        { "<leader>d", group = "Debug", icon = "" },
        { "<leader>e", desc = "Explorer", icon = "󰙅" },
        { "<leader>f", group = "Files", icon = "󰈮" },
        { "<leader>g", group = "Git", icon = "" },
        { "<leader>h", group = "Hunks", icon = "" },
        { "<leader>l", group = "LSP", icon = "" },
        { "<leader>n", group = "Notify", icon = "󰋚" },
        { "<leader>o", group = "OpenCode", icon = "󰚩" },
        { "<leader>q", desc = "Quit", icon = "󰅙" },
        { "<leader>Q", desc = "Quit All", icon = "󰅙" },
        { "<leader>s", group = "Search", icon = "" },
        { "<leader>t", group = "Test", icon = "󰙨" },
        { "<leader>u", group = "UI", icon = "" },
        { "<leader>x", group = "Xcode", icon = "" },
        { "g", group = "Goto" },
        { "gr", group = "LSP" },
        { "s", group = "Surround" },
        { "z", group = "Fold" },
        { "[", group = "Prev" },
        { "]", group = "Next" },
      },
      {
        mode = { "o", "x" },
        { "af", desc = "Function" },
        { "if", desc = "Function" },
        { "ac", desc = "Class" },
        { "ic", desc = "Class" },
        { "ao", desc = "Code block" },
        { "io", desc = "Code block" },
        { "at", desc = "Tag" },
        { "it", desc = "Tag" },
        { "ad", desc = "Digits" },
        { "id", desc = "Digits" },
        { "ae", desc = "Word (case)" },
        { "ie", desc = "Word (case)" },
        { "ag", desc = "Buffer" },
        { "ig", desc = "Buffer" },
        { "au", desc = "Function call" },
        { "iu", desc = "Function call" },
        { "aU", desc = "Function call (no dot)" },
        { "iU", desc = "Function call (no dot)" },
      },
    },
  },
  -- stylua: ignore
  keys = {
    { "<leader>?", function() require("which-key").show({ global = false }) end, desc = "Buffer Local Keymaps" },
  },
}
