require("items.apple")
require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.battery")
require("items.wifi")
require("items.volume")
require("items.input_source")
