return {
	"nvim-treesitter/nvim-treesitter",
	event = { "BufReadPost", "BufNewFile" },
	build = ":TSUpdate",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"html",
			"css",
			"javascript",
			"typescript",
			"tsx",
			"go",
			"gomod",
			"gosum",
			"gowork",
			"java",
			"kotlin",
			"python",
			"groovy",
			"xml",
			"sql",
			"json",
			"yaml",
			"graphql",
			"dockerfile",
			"gitignore",
			"toml",
			"lua",
		},
		auto_install = true,
		sync_install = false,
		highlight = { enable = true },
		indent = { enable = true },
	},
}
