# Terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# General
set -g mouse on
set -g mode-keys vi

set -g base-index 1
set -g renumber-windows on

# Reload config
unbind r 
bind r source-file ~/.tmux.conf

# Splits
unbind %
bind \\ split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Windows
bind c new-window -c "#{pane_current_path}"

# Pane resize
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# Copy mode (Vim style)
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Y send -X copy-line-and-cancel

# Notes
bind-key C-n command-prompt -p "Note name:" \
  "new-window -c ~/notes 'nvim \"%%.md\"'"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'

set -g @continuum-restore "on"

# Status bar 
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "basic"

set -g @mode_indicator_prefix_prompt ' WAIT '
set -g @mode_indicator_copy_prompt  ' COPY '
set -g @mode_indicator_sync_prompt  ' SYNC '
set -g @mode_indicator_empty_prompt ' TMUX '

set -g @mode_indicator_prefix_mode_style "bg=#{@thm_red},fg=#{@thm_crust}"
set -g @mode_indicator_copy_mode_style  "bg=#{@thm_yellow},fg=#{@thm_crust}"
set -g @mode_indicator_sync_mode_style  "bg=#{@thm_mauve},fg=#{@thm_crust}"
set -g @mode_indicator_empty_mode_style "bg=#{@thm_green},fg=#{@thm_crust}"

set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_current_text " #{b:pane_current_path}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_default_text "#W"

set -g status-justify centre
set -g status-left-length 100
set -g status-right-length 100
set -g @catppuccin_status_left_separator "█"
set -g status-left ""
set -g status-right ""
set -ag status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{tmux_mode_indicator}"

run "$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm"
