# Terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# General
set -g mouse on
set -g mode-keys vi

set -g base-index 1
set -g renumber-windows on

# Reload config
unbind r 
bind r source-file ~/.tmux.conf

# Splits
unbind %
bind \\ split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Windows
bind c new-window -c "#{pane_current_path}"

# Pane resize
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# Copy mode (Vim style)
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Y send -X copy-line-and-cancel

bind -r e split-window -h \
  "nvim ~/Documents/notes/ideas/$(date +'%Y-%m-%d').md"

bind -r o split-window -h \
  "nvim ~/Documents/notes/todo/$(date +'%Y-%m-%d').md"

bind -r v split-window -h -c "#{pane_current_path}" "zsh -c 'nvim; exec zsh'"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'

set -g @mode_indicator_prefix_prompt ' 󰔟 wait '
set -g @mode_indicator_copy_prompt  '  copy '
set -g @mode_indicator_sync_prompt  '  sync '
set -g @mode_indicator_empty_prompt '  tmux '

set -g @mode_indicator_prefix_mode_style "bg=#{@thm_red},fg=#{@thm_surface_0}"
set -g @mode_indicator_copy_mode_style  "bg=#{@thm_yellow},fg=#{@thm_surface_0}"
set -g @mode_indicator_sync_mode_style  "bg=#{@thm_mauve},fg=#{@thm_surface_0}"
set -g @mode_indicator_empty_mode_style "bg=#{@thm_green},fg=#{@thm_surface_0}"

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_status_background "none"

set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_text_color "#{@thm_surface_0}"
set -g @catppuccin_window_number_color "#{@thm_overlay_2}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_number "#I"
set -g @catppuccin_window_current_text_color "#{@thm_surface_1}"
set -g @catppuccin_window_current_number_color "#{@thm_maroon}"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_number "#I"

set -g status-justify centre
set -g status-left-length 100
set -g status-right-length 100

set -g status-style "bg=default,fg=#{@thm_fg}"

set -g status-left ""
set -g status-left "#{tmux_mode_indicator}"

set -g status-right ""
set -ga status-right "#[bg=#{@thm_mauve},fg=#{@thm_surface_0}]  #S "
set -ag status-right "#[bg=default] "
set -ga status-right "#[bg=#{@thm_yellow},fg=#{@thm_surface_0}] 󰝰 #{b:pane_current_path} "

run "$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm"
